_TOP_PART_

_EXTRAS_LIST_

_ROOMS_LIST_

_CANCELLATION_POLICY_

<br />
<hr>
<center>	
<p>
  _INVOICE_THANK_YOU_LINE_
  _INVOICE_HAVE_QUESTIONS_LINE_  
</p>		
<small>_INVOICE_DISCLAIMER_LINE_
<br /><br />&copy; _YOUR_COMPANY_NAME_. _ALL_RIGHTS_RESERVED_</small>
</center>